### ISSUE TITLE
Automatic creation of releases.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#111] opened 2022-01-02 01:51 UTC
Can a beta release be created twice a day.

It goes by this format 

year.month.number (number increments by 1 every beta)

**Comment by webdev03** [comment] 2022-01-02 02:01
Is it time to copy Ninetails?

**Comment by webdev03** [comment] 2022-01-02 02:04
You should learn Github Actions, it's quite fun. You can just `setup-node` with node 16, setup the git author, then make a script to get the date and `npm version`, then `git push --follow-tags`.

**Comment by JaydenDev** [comment] 2022-01-02 02:07
> You should learn Github Actions, it's quite fun. You can just `setup-node` with node 16, then make a script to get the date and `npm version`, then EndBug/add-and-commit with the git flag `--follow-tags`. I can set this up for you if you would like, but then can you first move the repo to the organisation?

If I have to do it know it won't be happening, or it'll just suck. 

Update not doing it, closing.

**Comment by JaydenDev** [comment] 2022-01-02 02:07
@webdev03 refused to do it, he's the only contributor. Closing.

**Comment by webdev03** [comment] 2022-01-02 02:08
I can do it! But it should be in a separate repo.

**Comment by webdev03** [comment] 2022-01-02 02:20
`.number` will be hard to do, so I'll just make it the current day and `-beta`.

**Comment by JaydenDev** [comment] 2022-01-02 02:31
@webdev03 alright!

**Comment by webdev03** [comment] 2022-01-02 02:37
Look, I made it so you and I can manually trigger it, it makes the tag. I don't know how to automate publishing it, though.

**Comment by webdev03** [comment] 2022-01-02 02:41
Edit, also, it says something about a PAT (personal access token) for the repo if we want the automatic releaser (the one that builds binaries) to work.

**Comment by JaydenDev** [comment] 2022-01-02 02:50
@webdev03 make it all one action.

**Comment by webdev03** [comment] 2022-01-02 02:52
What about stable builds?

**Comment by JaydenDev** [comment] 2022-01-02 03:53
@webdev03 stable builds are released manually.

**Comment by webdev03** [comment] 2022-01-02 03:54
Yes, I know. But the problem is that it won't trigger the action. I'll do that in.. *checks* about 10 minutes (sorry got distracted)

**Comment by JaydenDev** [comment] 2022-01-02 03:55
> Yes, I know. But the problem is that it won't trigger the action. I'll do that in.. _checks_ about 10 minutes (sorry got distracted)

since beta builds will be automatic, you can have an action for beta builds, then one for manually created releases.

**Comment by webdev03** [comment] 2022-01-02 03:59
I *think* it should build now, but I don't think we can make them "un-draft" automatically without doing something to the Forge configuration.

**Comment by JaydenDev** [comment] 2022-01-02 04:01
I can finish the creation I just need it at least semi-automatic

**Comment by webdev03** [comment] 2022-01-02 04:01
Ok, semi automatic testing initiated.

**Comment by webdev03** [comment] 2022-01-02 04:05
It seems to have worked, but only on the last test I did an hour ago. I am checking the docs.

**Comment by JaydenDev** [comment] 2022-01-02 04:07
2022.1.0-beta?
No its 22.1.100
*the numbers at the end start at 100

**Comment by JaydenDev** [comment] 2022-01-02 04:09
if you want to use the old dev method of 22.1.daynumber

**Comment by webdev03** [comment] 2022-01-02 04:23
I told you that I don't know how to increment with Actions (maybe by a file in the repo?) so you can change the code in https://github.com/The-Catalyst-Browser-Project/ci-auto-release/blob/main/auto.js to do whatever you want.

**Comment by JaydenDev** [comment] 2022-01-02 04:24
> I told you that I don't know how to increment with Actions (maybe by a file in the repo?) so you can change the code in https://github.com/The-Catalyst-Browser-Project/ci-auto-release/blob/main/auto.js to do whatever you want.

you can use day at the end and just update the script every month.
since it is
year.month.day it should be fairly easy right?

**Comment by webdev03** [comment] 2022-01-02 04:24
Y.M.D is already there. You mean by removing first two digits?

**Comment by JaydenDev** [comment] 2022-01-02 04:27
yeah so its 22 instead of 2022

**It was at this time I thought that this would be a mistake, this would make the script not Y3K compliant, it would... break in the year 3000. **

**Comment by webdev03** [comment] 2022-01-02 04:28
Not Y3K. You mean to say, 2100.

**Comment by JaydenDev** [comment] 2022-01-02 04:28
oh...

**Comment by JaydenDev** [comment] 2022-01-02 04:29
well, including the first 2 digits should be fine til 2.1k

**Comment by JaydenDev** [comment] 2022-01-02 04:31
@webdev03 
if you could add "(Tabby Beta)" at the end of the name of every release **BEFORE 1.0** **NOT INCLUDING PRE-RELEASES**
add it to the end of the name of every tabby beta

**Comment by webdev03** [comment] 2022-01-02 04:32
Can you give me an example of what to put "Tabby beta" and what to not?

**Comment by JaydenDev** [comment] 2022-01-02 04:33
i have to go soon but pretty much
21.12.100 all the way to the last beta BEFORE 1.0 (not releases with the -prerel or -prerelease ending)
Correct caps
(Tabby Beta)

**Comment by JaydenDev** [comment] 2022-01-02 04:33
DONT mess this up, if you are still confused DONT TRY to do it at all.

**Comment by webdev03** [comment] 2022-01-02 04:33
I understand.

**Comment by webdev03** [comment] 2022-01-02 04:35
Actually, I don't understand. I'll undo my change.

**Comment by webdev03** [comment] 2022-01-02 04:45
@JaydenDev this should be done, I tested, automation works, so I'll close this. If you have a problem with the tag names, feel free to reach out at https://github.com/The-Catalyst-Browser-Project/ci-auto-release/

**Closed** 2022-01-02 04:54 UTC
Labels: help wanted, question, high priority

**Comment by JaydenDev** [comment] 2022-01-02 16:27
@webdev03 it does work!
