### ISSUE TITLE
[Bug]: Bookmark toolbar not showing

### ISSUE THREAD

**Issue by texstar** [JaydenDev/Catalyst#230] opened 2022-05-31 01:06 UTC
### Steps to reproduce the issue?

I mark to show bookmark toolbar but it fails to show. Debian pkg.

### What happened?

Nothing happens.

### Version

3.1.1

**Comment by JaydenDev** [comment] 2022-05-31 01:08
Just a question, do you actively use the Catalyst browser?

**Comment by JaydenDev** [comment] 2022-05-31 01:13
Can't reproduce bug. I checked 'Show Bookmarks' myself and the bookmarks bar showed. What I think happened, is that either there was a localStorage issue on your device, or you don't have any bookmarks set. Please verify that you have bookmarks saved.

**Comment by texstar** [comment] 2022-05-31 06:15
> 

No. I found it on Electron Apps and thought ooooh a new browser to try. Maybe it can go into our software repository for PCLinuxOS.

**Comment by texstar** [comment] 2022-05-31 06:33
> Can't reproduce bug. I checked 'Show Bookmarks' myself and the bookmarks bar showed. What I think happened, is that either there was a localStorage issue on your device, or you don't have any bookmarks set. Please verify that you have bookmarks saved.

I tried to bookmarks a couple of sites. I have no idea what is going on but 2 others reported the same. Maybe it doesn't like us.  Everything else seems to be functioning within normal parameters.  Thanks for the reply.

**Comment by JaydenDev** [comment] 2022-05-31 14:09
> > 
> 
> No. I found it on Electron Apps and thought ooooh a new browser to try. Maybe it can go into our software repository for PCLinuxOS.

Sweet! Anyone is allowed to package my software into their repositories. Just make sure to mark it as unofficial!

**Comment by JaydenDev** [comment] 2022-05-31 14:15
Try clearing your localStorage
1. Press CTRL + I (or CTRL + A and click Dev Tools)
2. Click console
3. Run:
```js
localStorage.clear()
```
Then all your settings, flags, and bookmarks will be cleared.

**Comment by texstar** [comment] 2022-05-31 19:46
/usr/lib/catalyst/resources/app/src/firstTime.js not  FirstTime.js

**Comment by JaydenDev** [comment] 2022-05-31 20:06
### Testing the new source
You can test the new source by pasting the following into your terminal. **MAKE SURE YOU HAVE NPM INSTALLED!**
```bash
git clone https://github.com/JaydenDev/Catalyst
cd Catalyst
npm install
npm run make
cd out
ls
```
Then cd to the directory of the compiled binary or package.

**Comment by texstar** [comment] 2022-06-01 22:48
No bookmark toolbar yet. I'll wait for the next release and see what happens. I did get a new menu option on launch if I wanted to customize catalyst.

**Comment by JaydenDev** [comment] 2022-06-02 00:03
> No bookmark toolbar yet. I'll wait for the next release and see what happens. I did get a new menu option on launch if I wanted to customize catalyst. For the record, we are using the node.js/npm LTS release 16.15.0.

Yes, I'm pretty sure the 'new menu option on launch' you speak of is the banner that shows up upon first launch. When you clear localStorage or install Catalyst for the first time that shows up. That's a welcoming banner.

**Comment by texstar** [comment] 2022-06-03 02:09
I deleted the .config/catalyst folder before launching so that is the reason the banner showed up. Thanks for the information about 4.0. Good luck with your browser.

**Comment by 3oheicrw** [comment] 2022-07-18 05:54
Bookmarking is just broken for me. I clicked on the star and it does nothing. There is also no bookmark bar.

**Comment by JaydenDev** [comment] 2022-07-18 14:44
> Bookmarking is just broken for me. I clicked on the star and it does nothing. There is also no bookmark bar.
Enabled in settings?

**Comment by 3oheicrw** [comment] 2022-07-20 00:34
> > Bookmarking is just broken for me. I clicked on the star and it does nothing. There is also no bookmark bar.
> 
> Enabled in settings?

When the browser start it opened Preferences automatically and I have to close it. Do you think I didn't see the settings? :smile:

**Comment by JaydenDev** [comment] 2022-09-03 21:09
This is a confirmed issue as of the latest release of Catalyst.

**Comment by JaydenDev** [comment] 2022-09-05 17:51
@texstar Fixed in the latest point release.

**Closed by JaydenDev** 2022-09-05 17:51 UTC
Labels: bug
